### ISSUE TITLE
Add logging to specification

### ISSUE THREAD

**Issue by leggetter** [Nexmo/server-sdk-specification#1]
Essential logging for me are:
1. The raw request going from the library to the Nexmo API
2. The raw response coming back from the Nexmo API

These can be invaluable when debugging or when handling support queries.

**Comment by pvela** [comment]
Ability to turn logging on and off through options.
Use a platform standard log if available (for ex. native java logging)
Log Errors and Warnings by default

**Comment by tjlytle** [comment]
I think this covers everything. Added the concept of interface logging for situations like PHP where you don't generally write directly to `error_log`, rather use a PSR-1 compliant logger, and configure where / how verbose you want logging to be with that.

Also, adding request / response to error and exceptions means services like Rollbar / Bugsnap / etc may (depending on how it's done, how much of a dump they provide) give you request / response without the need of any additional logs.

**Comment by tjlytle** [comment]
@pvela @leggetter Any issues with the commit? If not, I'll go ahead and merge.

**Comment by pvela** [comment]
Looks Good @tjlytle Please Go ahead and Merge.
