### ISSUE TITLE
[Discuss] It should be possible to append additional information to the user agent

### ISSUE THREAD

**Issue by leggetter** [Nexmo/server-sdk-specification#10]
If a library uses a Nexmo client library it should be possible for that client to add additional information to the [library user agent](https://github.com/Nexmo/client-library-specification/blob/master/SPECIFICATION.md#reporting).

e.g. if the library user agent is `nexmo-node/1.0.0/5.0` it should be possible to append information to that. For the Nexmo Command Line interface 1.0 release this may result in the user agent being `nexmo-node/1.0.0/5.0/nexmo-cli/1.0.0`.

Related: https://github.com/Nexmo/nexmo-cli/issues/38

**Comment by tjlytle** [comment]
@leggetter, this works for me. @timcraft @pvela @smithrobs any issues with this? Would like to get added to the current libraries soon.

**Comment by timcraft** [comment]
Would both the name and the version have to be specified (i.e. no-op if only one of the options is set)? Regarding extensibility--what if you want to capture more info besides the app name & version in future?

Not very common, but Stripe uses a custom header with a JSON encoded hash/dict:

https://github.com/stripe/stripe-ruby/blob/master/lib/stripe.rb#L220-L235

https://github.com/stripe/stripe-ruby/blob/master/lib/stripe.rb#L290

**Comment by tjlytle** [comment]
I think if we need more than app / version in the future, we'd go with the header. My feeling adding this is about the max we'd every want to push into a user agent (and arguably more than is optimal). However, I doubt many people will even use the app + version. Mostly for us (Nexmo) tracking usage of things like the CLI tool, or perhaps examples / utilities / etc. 

From my perspective, requiring both app name and version makes sense. @leggetter does that would for you and @sammachin?

**Comment by smithrobs** [comment]
I foresee no issues in implementing this. Makes sense.
