### ISSUE TITLE
Contributing template

### ISSUE THREAD

**Issue by timcraft** [Nexmo/server-sdk-specification#11]
README.md template is still lacking content for the Contributing section.

[CONTRIBUTING.md template](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) would be useful.

**Comment by tjlytle** [comment]
Indeed, will draft that as a PR.

**Comment by judy2k** [comment]
Can I recommend that we have this as a short blurb in the README, linking to a Wiki document (or something) in this repo?

I feel like the contribution guidelines are something that is going to evolve with time, and it would be best to keep it in one place.

**Comment by lornajane** [comment]
This is served by the Repo standards (internal only at the moment) that include templates for README and CONTRIBUTING files https://nexmoinc.atlassian.net/wiki/spaces/DEVREL/pages/1146683965/GitHub+Repo+Standards
