### ISSUE TITLE
[Reporting] Required user-agent format is not compatible with spec

### ISSUE THREAD

**Issue by smithrobs** [Nexmo/server-sdk-specification#16]
In ```SPECIFICATION.md```: "Must set a user-agent with the following format: LIBRARY-NAME/LIBRARY-VERSION/LANGUAGE-VERSION"

This format is not compliant with the [RFC7231](https://tools.ietf.org/html/rfc7231) spec. Section [5.5.3](https://tools.ietf.org/html/rfc7231#section-5.5.3) states that only NAME/VERSION is supported, not NAME/VERSION/VERSION (or any other variant). Multiple NAME/VERSION values are supported. Compliant example:

```User-Agent: nexmo-dotnet/1.0 dotnet/1.0```

I ran into this because .NET parses and validates the user-agent string before adding it to the request. It will not allow the string as required in the Nexmo client-library-specification.

**Comment by tjlytle** [comment]
@smithrobs can you verify that this change passes the validation?

**Comment by smithrobs** [comment]
@tjlytle It does for me in .NET land, yes thanks! 👍
