### ISSUE TITLE
Document the correct encoding to use based on what is supported by the API

### ISSUE THREAD

**Issue by pvela** [Nexmo/server-sdk-specification#3]
Encoding on client library requirement should be documented based on the functionality of API. This is to ensure all characters in the text are sent successfully like for ex accented characters, extended characters from GSM Spec and unicode characters.

Is this universal for all entities like sms, voice etc.

Does nexmo API support unicode characters? If yes should the client library encode them in certain characterset? My assumption is to encode all text by UTF-8 only if the incoming text do not contain unicode characters - needs confirmation from the core eng team.

**Comment by lornajane** [comment]
Pretty sure this is correctly supported in the current library versions, so closing for now but let's get issues opened on individual libraries for any situations where that's not the case.
