### ISSUE TITLE
Should transfer the error message and error code returned by the API

### ISSUE THREAD

**Issue by pvela** [Nexmo/server-sdk-specification#4]
Error response from API’s be translated to language specific error objects with same error codes and messages sent by API

**Comment by tjlytle** [comment]
I'll should be adding a PR with a small change to the error section soon, but for the most part I think the answer is yes, just pass on the code and error. In the case of legacy APIs that don't use status codes, the `class` of error (user / API) may need to be distinguished using the error code (for APIs that use status codes, that's just a `4xx` vrs `5xx`).
